# Generated by Django 3.2.7 on 2021-09-24 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('time_started', models.DateTimeField()),
                ('time_ended', models.DateTimeField()),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_team_score', models.SmallIntegerField()),
                ('away_team_score', models.SmallIntegerField()),
                ('confirmed', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sg', 'Single Point'), ('tk', 'Tink'), ('sk', 'Sink'), ('bs', 'Bounce Sink'), ('ps', 'Partner Sink'), ('ss', 'Self Sink'), ('ff', 'Fifa'), ('fg', 'Field Goal'), ('fv', 'Five'), ('ut', 'Untracked')], default='sg', max_length=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='games.game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
