# Generated by Django 3.1.4 on 2021-03-21 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStarted', models.DateTimeField()),
                ('timeSaved', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPointsToWin', models.IntegerField()),
                ('singlePointsValue', models.IntegerField()),
                ('tinkPointsValue', models.IntegerField()),
                ('sinkPointsValue', models.IntegerField()),
                ('bounceSinkPointsValue', models.IntegerField()),
                ('partnerSinkPointsValue', models.IntegerField()),
                ('selfSinkPointsValue', models.IntegerField()),
                ('winByTwo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfPoint', models.CharField(choices=[('PT', 'regular point'), ('SS', 'self sink'), ('TK', 'tink'), ('SK', 'sink'), ('BS', 'bounce sink'), ('PS', 'partner sink')], default='PT', max_length=2)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoredOn', to='games.game')),
            ],
        ),
    ]
