# Generated by Django 3.1.4 on 2021-04-02 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0002_auto_20210402_2026'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='scored_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_on', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='point',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='team_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='friends.friend'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='friends.friend'),
        ),
    ]
