# Generated by Django 3.1.4 on 2021-03-21 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='scoredOn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='point',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='playerFour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='playerOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='playerThree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='playerTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to=settings.AUTH_USER_MODEL),
        ),
    ]
