# Generated by Django 3.1.4 on 2021-03-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210321_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='statType',
            field=models.CharField(choices=[('JP', 'Just Points'), ('RS', 'Regular Stats'), ('FS', 'Full Stats')], default='RS', max_length=2),
        ),
    ]
