# Generated by Django 3.1.4 on 2021-03-14 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210312_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timeStarted',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
