# Generated by Django 3.1.4 on 2021-06-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210428_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
    ]
