# Generated by Django 3.2.6 on 2021-08-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_point_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('sg', 'Single Point'), ('tk', 'Tink'), ('sk', 'Sink'), ('bs', 'Bounce Sink'), ('ps', 'Partner Sink'), ('ss', 'Self Sink'), ('ff', 'Fifa'), ('fg', 'Field Goal'), ('fv', 'Five'), ('ut', 'Untracked')], default='sg', max_length=2),
        ),
    ]
