# Generated by Django 3.1.4 on 2021-03-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20210314_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='numPointsToWin',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
