# Generated by Django 3.1.4 on 2021-03-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_numpointstowin'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bounceSinkPointsValue',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='partnerSinkPointsValue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='selfSinkPointsValue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='singlePointsValue',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='sinkPointsValue',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='tinkPointsValue',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
