# Generated by Django 3.1.4 on 2021-03-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20210315_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winByTwo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
