# Generated by Django 3.1.4 on 2021-03-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_winbytwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPointsToWin', models.IntegerField()),
                ('singlePointsValue', models.IntegerField()),
                ('tinkPointsValue', models.IntegerField()),
                ('sinkPointsValue', models.IntegerField()),
                ('bounceSinkPointsValue', models.IntegerField()),
                ('partnerSinkPointsValue', models.IntegerField()),
                ('selfSinkPointsValue', models.IntegerField()),
                ('winByTwo', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='bounceSinkPointsValue',
        ),
        migrations.RemoveField(
            model_name='game',
            name='numPointsToWin',
        ),
        migrations.RemoveField(
            model_name='game',
            name='partnerSinkPointsValue',
        ),
        migrations.RemoveField(
            model_name='game',
            name='selfSinkPointsValue',
        ),
        migrations.RemoveField(
            model_name='game',
            name='singlePointsValue',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sinkPointsValue',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tinkPointsValue',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winByTwo',
        ),
    ]
