# Generated by Django 3.1.4 on 2021-03-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20210315_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timeSaved',
            field=models.DateTimeField(),
        ),
    ]
