# Generated by Django 3.1.4 on 2021-02-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfLitter', models.CharField(choices=[('IND', 'individual piece of litter'), ('GRO', 'grocery bag of litter'), ('GAR', 'garbage bag of litter')], default='IND', max_length=3)),
                ('amount', models.IntegerField()),
                ('timeCollected', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
