# Generated by Django 3.1.4 on 2021-03-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='scoredOn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
