# Generated by Django 3.1.4 on 2021-04-02 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pd', 'Pending'), ('ac', 'Accepted'), ('dn', 'Denied')], max_length=2)),
                ('wins', models.SmallIntegerField()),
                ('losses', models.SmallIntegerField()),
                ('league', models.CharField(choices=[('ur', 'Unranked'), ('br', 'Bronze'), ('sv', 'Silver'), ('gd', 'Gold'), ('dm', 'Diamond')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
