# Generated by Django 3.1.4 on 2021-03-12 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamCaptain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamCaptain', to=settings.AUTH_USER_MODEL)),
                ('teammate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
