# Generated by Django 3.1.4 on 2021-04-02 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamOne', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamTwo', to=settings.AUTH_USER_MODEL),
        ),
    ]
