# Generated by Django 3.1.4 on 2021-03-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='league',
        ),
    ]
