# Generated by Django 3.2.6 on 2021-08-05 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamOne', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamTwo', to=settings.AUTH_USER_MODEL),
        ),
    ]
