# Generated by Django 3.1.4 on 2021-03-20 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_remove_friend_league'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
