# Generated by Django 3.2.6 on 2021-08-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='league',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='wins',
        ),
    ]
