# Generated by Django 3.1.4 on 2021-04-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20210402_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='team_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
