# Generated by Django 3.1.4 on 2021-04-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friend_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('pd', 'Pending'), ('ac', 'Accepted'), ('dn', 'Denied'), ('nt', 'Nothing')], max_length=2),
        ),
    ]
