# Generated by Django 3.2.6 on 2021-08-12 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0003_auto_20210806_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='team_name',
        ),
        migrations.AlterField(
            model_name='friend',
            name='team_captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammate', to=settings.AUTH_USER_MODEL),
        ),
    ]
