# Generated by Django 3.1.4 on 2021-03-20 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0003_delete_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('DE', 'Denied'), ('AC', 'Accepted')], default='PD', max_length=2)),
                ('timeRequested', models.DateTimeField(auto_now_add=True)),
                ('timeRespondedTo', models.DateTimeField(auto_now=True)),
                ('friendOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendOne', to=settings.AUTH_USER_MODEL)),
                ('friendTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendTwo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
