# Generated by Django 3.1.4 on 2021-05-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20210428_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='league',
            field=models.CharField(choices=[('ur', 'Unranked'), ('br', 'Bronze'), ('sv', 'Silver'), ('gd', 'Gold'), ('dm', 'Diamond')], default='ur', max_length=2),
        ),
        migrations.AlterField(
            model_name='friend',
            name='losses',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('bl', 'Blocked'), ('pd', 'Pending'), ('ac', 'Accepted'), ('nt', 'Nothing')], default='pd', max_length=2),
        ),
        migrations.AlterField(
            model_name='friend',
            name='wins',
            field=models.SmallIntegerField(default=0),
        ),
    ]
